### ISSUE TITLE
MasterDetailPage

### ISSUE THREAD

**Issue by brunoportess** [pictos/CoPiloto#2]
No modelo de navegação do projeto, como faço por exemplo.... estou na tela de login e caso login seja validado quero que a navegação seja feita para uma MasterDetailPage, a qual não fica dentro de uma NavigationPage como a propriedade "SetarMainPage" faz. Como proceder nesse caso? Criar um metodo exclusivo para navegação sem o encapsulamento da NavigationPage para esse caso especifico da MasterDetailPage?

**Comment by pictos** [comment]
@brunoportess , desculpe a demora, só hj que vi a pergunta. Isso é tranquilo de fazer, e inclusive o @balivo  tem uma série excelentes de vídeos sobre navegação no Xamarin Forms(sem frameworks). A vídeo aula que trata de navegação usando Master Detail é essa:

https://youtu.be/JUrgHeC2JcE

Na live da próxima semana (08/10) irei implementar uma Master Detail e navegação pra ela, ainda sim sugiro que assista essa aulas.

**Comment by brunoportess** [comment]
Que bacana, irei assistir esse video e ver a live tambem entao. Agradeço
