### ISSUE TITLE
NavigationService - Locator

### ISSUE THREAD

**Issue by brunoportess** [pictos/CoPiloto#3]
Olá!
A navegação funciona perfeitamente para os arquivos que ficam na raiz das pastas ViewModels e Views. Porém, quando estão em subpastas, os mesmo não funcionam porque quando o Activator vai criar a instancia, tenta achar o arquivo na raiz da pasta Views. Como ficaria a adaptação desse metodo para localizar em subpastas.

Por exemplo, tenho a subpasta ViewModels\Taxas e Views\Taxas, sempre seguinte o mesmo padrao de subpastas para as views e viewmodels.

**Comment by brunoportess** [comment]
Não sei se foi a melhor forma, com toda certeza da pra deixar mais nitido e performatico, mas fiz da seguinte maneira

var nameSolution = viewModelType.AssemblyQualifiedName.Split('.')[0];
                var viewName = $"{viewModelTypeName.Replace("ViewModel", "")}Page";
                var nameDirFile = viewModelType.FullName.Replace($"{nameSolution}.ViewModels.","");
                nameDirFile = nameDirFile.Replace("ViewModel","Page");
                
                var viewTypeName = $"{nameSolution}.Views.{nameDirFile}";
                viewType = Type.GetType(viewTypeName);
                page = Activator.CreateInstance(viewType) as Page;
                CriarMapeamento(page.GetType(), viewModelType);

**Comment by pictos** [comment]
Olá @brunoportess , é uma maneira de resolver... A que eu uso para este caso é:


```cs
Page Locator<TViewModel>(object[] args) where TViewModel : BaseViewModel
        {
            var viewModelType = typeof(TViewModel);
            var viewModelTypeName = viewModelType.Name;
            var viewType = VerificarPage(viewModelType);
            Page page;
            if (viewType == null)
            {
                var name         = typeof(BaseViewModel).AssemblyQualifiedName.Split('.')[0];
                var pageName     = viewModelTypeName.Substring(0, viewModelTypeName.Length - 9);
                var folder       = pageName + ".";
                var viewTypeName = $"{name}.Views.{folder}{pageName}Page";
              
                viewType = Type.GetType(viewTypeName);
                page = Activator.CreateInstance(viewType) as Page;
                CriarMapeamento(page.GetType(), viewModelType);
            }
            else
                page = Activator.CreateInstance(viewType) as Page;


            var viewModel = Activator.CreateInstance(viewModelType);

            if (page != null)
                page.BindingContext = viewModel;

            return page;
        }
```

Não se te precisar qual dos jeitos é mais performático. Mas é sempre bom ter mais opções né?

Abraços.
